---
- hosts: server
  gather_facts: false
  become: yes
  become_user: ubuntu
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  tasks:
    - name: Create replicaset object
      k8s:
        state: present
        defination:
          api_Version: apps/v1
          kind: ReplicaSet
          metadata:
            name: java-webapp
            namespace: default
          spec:
            replicas: 2 # We'll get three identical pods
            selector:
                matchLabels:
                  app: java-webapp
            template:
              metadata:
                labels:
                  app: java-webapp
              spec:
                containers:
                - name: spring3appjava
                  image: 020038540642.dkr.ecr.us-east-2.amazonaws.com/spring3appjava:{{ version }}
                  ports:
                  - containerport: 8080
                imagePullSecrets:
                - name: us-east-2-ecr-registry
    - name: Create a service to access spring app
      k8s:
        state: present
        definition:
          apiversion: v1
          kind: service
          metadata:
            name: hello-node-webapp
            namespace: default
          spec:
            type: NodePort
            ports:
            - port: 8080
              nodeport: 30003
              protocol: TCP
            selector:
              app: java-webapp

